name: stock_tracking
description: An app for an Inventory Managment Application, designed for mobile.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.4.0
  introduction_screen: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true